### ISSUE TITLE
Not working after lateat amd driver update

### ISSUE THREAD

**Issue by leandrodiogenes** [AllyPal/Rog-Ally-Custom-Resolutions#2]
Not workinf after AMD_Graphic_DriverOnly_ROG_AMD_Z_V31.0.21029.6002_35393 update

**Comment by yoanhg421** [comment]
Second

**Comment by AllyPal** [comment]
This might help you:
https://github.com/AllyPal/Rog-Ally-Custom-Resolutions/wiki#common-problems

**Comment by leandrodiogenes** [comment]
ty so much
